### ISSUE TITLE
Support attaching data to each log

### ISSUE THREAD

**Issue by cjihrig** [hapijs/log#5]
Similar to the concept of a child logger. By attaching a set of data for each log users don't need to attach it "by hand."

**Comment by geek** [comment]
Maybe we can have a base set of `additionalFields` like `hostname`, `pid`, and `uri` <- the `server.info.uri`, then any custom supplied `additionalFields` can override these values if need be.

**Comment by Nargonath** [comment]
Seems like a good idea to me @geek . It provides interesting defaults that are not written in stone that you can easily override.
